### ISSUE TITLE
Hand off logging to system (or: log to stdout/stderr)

### ISSUE THREAD

**Issue by gersilex** [Tknika/serial2tcp-gateway#4] opened 2018-06-04 21:37 UTC
Hey. While working on porting this to python3 I discovered that we explicitly log to a file. We neither know if the is the desired log location, nor do we know if the running user has the permissions to create or write there.

Also, when running the application interactively (for testing and debugging) we have no output because everything is written to a file. This leaves the `systemctl status` and systemd journal empty as well.

What about logging to stdout and stderr? I already have a commit ready for you that will come shortly after the python3 port.

**Comment by bodiroga** [comment] 2018-06-14 07:20
Hi @gersilex!

Sorry for replying so late :sob: 

I agree that hardcoding the log path is not the best option, that's why the installer script takes care of creating the log file and giving appropriate permissions. What mechanism can we use to redirect the output when the problem is run as a daemon? Ummm... I suppose that systemd should have a mechanism for that, I will try to find some information about it.

Best regards,

Aitor

PS: PR will be merged after finding an alternative solution, don't worry.

**Comment by bodiroga** [comment] 2018-06-14 07:52
Ok, it seems that the modern way to manage log files is through systemd and its journal (see: https://unix.stackexchange.com/a/57243).

The journalctl utility allows to view log entries from a single service using:

sudo journalctl -u serial2tcp-gateway.service (add "-f" to view it dynamically)

There is no need to log to a file then :+1:

**Closed as completed** 2018-06-14 07:53 UTC

**Comment by gersilex** [comment] 2018-06-14 09:15
Exactly. Systemd is awesome and takes away the usual pain from the past. I love it! :)
